version: "3"

services:
  broker-mqtt-msname:
    image: eclipse-mosquitto
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - NEBULAE_MQTT:/mosquitto/data            
  store-mongo-msname:
    image: mongo:4
    ports:
      - "27017:27017"
    environment: 
        - storageEngine=wiredTiger
    volumes: 
      - NEBULAE_MONGO:/data/db
volumes: 
  NEBULAE_MQTT:
  NEBULAE_MONGO: